# Generated by Django 5.0 on 2024-06-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerowatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
