# Generated by Django 5.0 on 2024-06-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerowatch', '0002_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
